// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/echart/src/bar-echart.vue')['default']
    BaseEchart: typeof import('./src/components/echart/src/base-echart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBreadcrumb: typeof import('./src/components/main-header/c-cpns/header-breadcrumb.vue')['default']
    HeaderInfo: typeof import('./src/components/main-header/c-cpns/header-info.vue')['default']
    IEpElementPlus: typeof import('~icons/ep/element-plus')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    ImageUpload: typeof import('./src/components/image-upload/image-upload.vue')['default']
    LineEchart: typeof import('./src/components/echart/src/line-echart.vue')['default']
    MainHeader: typeof import('./src/components/main-header/main-header.vue')['default']
    MainMenu: typeof import('./src/components/main-menu/main-menu.vue')['default']
    MapEchart: typeof import('./src/components/echart/src/map-echart.vue')['default']
    PageComment: typeof import('./src/components/page-comment/page-comment.vue')['default']
    PageContent: typeof import('./src/components/page-content/page-content.vue')['default']
    PageEditor: typeof import('./src/components/page-editor/page-editor.vue')['default']
    PageModal: typeof import('./src/components/page-modal/page-modal.vue')['default']
    PagePanel: typeof import('./src/components/page-panel/page-panel.vue')['default']
    PageSearch: typeof import('./src/components/page-search/page-search.vue')['default']
    PieEchart: typeof import('./src/components/echart/src/pie-echart.vue')['default']
    RoseEchart: typeof import('./src/components/echart/src/rose-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/icon-select/src/Select.vue')['default']
  }
}
